include:
  - compose.db.yml

services:
  data-collector:
    extends:
      file: compose.yml
      service: data-collector
    command: /bin/sh -c "bun dev:db:push:force && bun dev"
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package*.json
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M
  dashboard:
    extends:
      file: compose.yml
      service: dashboard
    ports:
      - "2999:3000"
  pgadmin:
    image: dpage/pgadmin4:9.0.0
    container_name: pgadmin4_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1024M
    

volumes:
  pgadmin_data:
