include:
  - compose.db.yml

services:
  data-collector:
    build: ./apps/bptf-analyzer-data-collector
    ports:
      - "3001:3000"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
  dashboard:
    build: ./apps/bptf-analyzer-dashboard
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    restart: unless-stopped