services:
  db:
    image: postgres:12.22
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DASHBOARD_DB_USERNAME: ${DASHBOARD_DB_USERNAME}
      DASHBOARD_DB_PASSWORD: ${DASHBOARD_DB_PASSWORD}
    volumes:
      - bptf-analyzer-db:/var/lib/postgresql/data
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M

volumes:
  bptf-analyzer-db: