services:
  db:
    image: postgres:12.22
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DASHBOARD_DB_USERNAME: ${DASHBOARD_DB_USERNAME}
      DASHBOARD_DB_PASSWORD: ${DASHBOARD_DB_PASSWORD}
    volumes:
      - bptf-analyzer-db:/var/lib/postgresql/data
      - ./add-dashboard-user-db.sh:/docker-entrypoint-initdb.d/add-dashboard-user-db.sh
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1024M

volumes:
  bptf-analyzer-db: