include:
  - compose.db.yml

services:
  data-collector:
    build: ./apps/bptf-analyzer-data-collector
    depends_on:
      - db
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - RETENTION_HOURS=6
      - CLEANUP_INTERVAL_MINUTES=15
  dashboard:
    build: ./apps/bptf-analyzer-dashboard
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DASHBOARD_DB_USERNAME=${DASHBOARD_DB_USERNAME}
      - DASHBOARD_DB_PASSWORD=${DASHBOARD_DB_PASSWORD}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    depends_on:
      - db
    restart: unless-stopped